### ISSUE TITLE
Make checkpoints public

### ISSUE THREAD

**Issue by ezhang7423** [young-geng/CQL#7]
Hi, would it be possible to release the checkpoints for this implementation? Would be very grateful for this.

**Comment by young-geng** [comment]
Unfortunately I don't have saved checkpoints for this. However, it takes less than a day to train one from scratch on a single GPU. If that is still too long, you might want to check out my [JAX implementation of CQL](https://github.com/young-geng/JaxCQL), which can train a CQL agent on a single GPU in around 2 hours.

**Comment by ezhang7423** [comment]
Thank you for the response!
